import { appAlert, appPrompt } from '../../../lib/app-dialog';
import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { supabase } from '../../../lib/supabase/client';

import { useTranslation } from '../../../locales/LanguageContext';

type Row=Record<string, any>;
const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n)||0);
const Status=({v}:{v:string})=><span className={`status ${/ditolak|closed|rejected|withdrawn|cancelled/i.test(v)?'red':/draft|pending|screening|assessment|menunggu/i.test(v)?'orange':/open|aktif|hired|disetujui|scheduled|diterima|ready/i.test(v)?'green':'blue'}`}>{v||'—'}</span>;
function Heading({title,desc,action,onAction}:{title:string;desc:string;action?:string;onAction?:()=>void}){return <div className="page-heading"><div><span className="group-title">TALENT · ATS V25</span><h1>{title}</h1><p>{desc}</p></div>{action&&<button className="primary" onClick={onAction}>{action}</button>}</div>}
function Modal({title,onClose,onSubmit,children,submit='Simpan'}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent)=>void;children:ReactNode;submit?:string}){return <div className="drawer-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><aside className="edit-drawer"><div className="drawer-head"><div><span>PROJECT BY TIRTA</span><h2>{title}</h2></div><button type="button" className="icon-btn" onClick={onClose}>×</button></div><form className="drawer-body" onSubmit={onSubmit}>{children}<div className="drawer-foot"><button type="button" className="secondary" onClick={onClose}>Batal</button><button className="primary">{submit}</button></div></form></aside></div>}
function Table({cols,rows}:{cols:string[];rows:Row[]}){return <div className="panel table-panel"><div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c}>{c.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{cols.map(c=><td key={c}>{c==='status'||c==='stage'?<Status v={String(r[c]??'—')}/>:c.includes('salary')||c.includes('nominal')||c.includes('proposed')?money(Number(r[c]||0)):String(r[c]??'—')}</td>)}</tr>):<tr><td className="empty-cell" colSpan={cols.length}>Belum ada data.</td></tr>}</tbody></table></div></div>}

export default function RecruitmentATSv25(){const {t}=useTranslation();
const [tab, setTab] = useState('command');
const [reqs, setReqs] = useState<Row[]>([]);
const [openings, setOpenings] = useState<Row[]>([]);
const [profiles, setProfiles] = useState<Row[]>([]);
const [apps, setApps] = useState<Row[]>([]);
const [interviews, setWawancara] = useState<Row[]>([]);
const [offers, setPenawaran] = useState<Row[]>([]);
const [handoffs, setHandoffs] = useState<Row[]>([]);
const [modal, setModal] = useState<string | null>(null);
const [msg, setMsg] = useState('');
 const load=async()=>{const [a,b,c,d,e,f,g]=await Promise.all([supabase.from('hris_recruitment_requisitions_v25').select('*').order('created_at',{ascending:false}),supabase.from('hris_recruitment_openings_v25').select('*').order('created_at',{ascending:false}),supabase.from('hris_candidate_profiles_v25').select('*').order('created_at',{ascending:false}),supabase.from('hris_recruitment_applications_v25').select('*').order('created_at',{ascending:false}),supabase.from('hris_recruitment_interviews_v25').select('*').order('scheduled_at'),supabase.from('hris_recruitment_offers_v25').select('*').order('created_at',{ascending:false}),supabase.from('hris_recruitment_onboarding_handoffs_v25').select('*').order('created_at',{ascending:false})]);setReqs(a.data||[]);setOpenings(b.data||[]);setProfiles(c.data||[]);setApps(d.data||[]);setWawancara(e.data||[]);setPenawaran(f.data||[]);setHandoffs(g.data||[]);const er=[a,b,c,d,e,f,g].find(x=>x.error);if(er)setMsg(er.error?.message||'Gagal memuat ATS');};
 useEffect(()=>{load()},[]);
 const active=apps.filter(x=>x.status==='Active').length, hired=apps.filter(x=>x.stage==='Diterima').length, pendingReq=reqs.filter(x=>x.status==='Menunggu Approval').length, pendingOffer=offers.filter(x=>x.status==='Menunggu Approval').length;
 const stages=['Screening','Interview','Assessment','Offering','Diterima','Rejected'];
 async function move(a:Row,stage:string){setMsg('');const {error}=await supabase.rpc('hris_v25_move_application',{p_application_id:a.id,p_to_stage:stage,p_note:null});if(error)setMsg(error.message);else await load()}
 async function decisionReq(r:Row,approve:boolean){const {error}=await supabase.rpc('hris_v25_approve_requisition',{p_id:r.id,p_approve:approve,p_note:null});if(error)setMsg(error.message);else load()}
 async function decisionOffer(r:Row,approve:boolean){const {error}=await supabase.rpc('hris_v25_approve_offer',{p_id:r.id,p_approve:approve,p_note:null});if(error)setMsg(error.message);else load()}
 async function handoff(a:Row){const start=await appPrompt(t('onboarding_start_date_prompt'),today());if(!start)return;const {error}=await supabase.rpc('hris_v25_hiring_handoff',{p_application_id:a.id,p_start_date:start,p_notes:'Handoff dari ATS V25'});if(error)setMsg(error.message);else load()}
 const pipeline=stages.map(s=>({stage:s,count:apps.filter(a=>a.stage===s).length}));
 return <><Heading title="Rekrutmen" desc="Permintaan tenaga kerja → lowongan → kandidat → alur kandidat → wawancara → penawaran → penerimaan → serah terima onboarding." action="＋ Pengajuan Kebutuhan" onAction={()=>setModal('req')}/><div className="mini-kpi-row"><div className="stat-card"><span>Lamaran Aktif</span><strong>{active}</strong></div><div className="stat-card"><span>Profil Kandidat</span><strong>{profiles.length}</strong></div><div className="stat-card"><span>Menunggu Approval</span><strong>{pendingReq+pendingOffer}</strong></div><div className="stat-card"><span>Diterima</span><strong>{hired}</strong></div></div>{msg&&<div className="alert">{msg}</div>}<div className="branch-nav">{[['command','Pusat Kendali'],['requisitions','Permintaan Tenaga Kerja'],['openings','Lowongan'],['candidates','Kandidat'],['pipeline','Alur Kandidat'],['interviews','Wawancara'],['offers','Penawaran'],['handoff','Serah Terima Onboarding']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {tab==='command'&&<div className="content-grid"><section className="web-card-group"><div className="panel-head"><div><h2>Ringkasan Tahapan</h2><p>Distribusi kandidat per tahap.</p></div></div><div className="mini-kpi-row">{pipeline.map(x=><div className="stat-card" key={x.stage}><span>{x.stage}</span><strong>{x.count}</strong></div>)}</div></section><div className="panel"><h2>Antrian Kendali</h2><p>Approval yang membutuhkan tindakan.</p><div className="request-list"><div><b>{pendingReq}</b><span>Pengajuan Kebutuhan menunggu approval</span></div><div><b>{pendingOffer}</b><span>Offer menunggu approval</span></div><div><b>{interviews.filter(x=>x.status==='Scheduled').length}</b><span>Wawancara terjadwal</span></div></div></div></div>}
 {tab==='requisitions'&&<><Heading title="Permintaan Tenaga Kerja" desc="Permintaan tenaga kerja sebelum lowongan dipublikasikan." action="＋ Buat Pengajuan Kebutuhan" onAction={()=>setModal('req')}/><Table cols={['request_no','posisi','departemen','jumlah_kebutuhan','target_tanggal','status']} rows={reqs}/><div className="panel table-panel"><div className="table-wrap"><table><tbody>{reqs.filter(r=>r.status==='Menunggu Approval').map(r=><tr key={r.id}><td><b>{r.request_no}</b></td><td>{r.posisi}</td><td><Status v={r.status}/></td><td><button className="primary" onClick={()=>decisionReq(r,true)}>Setujui</button> <button className="secondary" onClick={()=>decisionReq(r,false)}>Tolak</button></td></tr>)}</tbody></table></div></div></>}
 {tab==='openings'&&<><Heading title="Lowongan" desc="Lowongan yang berasal dari approved requisition." action="＋ Pembukaan Lowongan" onAction={()=>setModal('opening')}/><Table cols={['opening_no','posisi','departemen','lokasi','employment_type','headcount','status']} rows={openings}/></>}
 {tab==='candidates'&&<><Heading title="Profil Kandidat" desc="Master kandidat dengan deteksi email duplikat di level database." action="＋ Candidate" onAction={()=>setModal('candidate')}/><div className="toolbar-panel"><span>{profiles.length} candidate profile</span><button className="secondary" onClick={()=>setModal('application')}>＋ Buat Application</button></div><Table cols={['full_name','email','phone','city','source','created_at']} rows={profiles}/></>}
 {tab==='pipeline'&&<><Heading title="Candidate Pipeline" desc="Perpindahan tahap memakai RPC server-side dan stage history."/><div className="content-grid">{stages.map(s=><div className="panel" key={s}><div className="panel-head"><h3>{s}</h3><b>{apps.filter(a=>a.stage===s).length}</b></div>{apps.filter(a=>a.stage===s).slice(0,12).map(a=>{const p=profiles.find(x=>x.id===a.candidate_profile_id);return <div className="request-list" key={a.id}><div><b>{p?.full_name||'Candidate'}</b><span>{a.status}</span></div><select value={a.stage} onChange={e=>move(a,e.target.value)}>{stages.map(x=><option key={x}>{x}</option>)}</select>{a.stage==='Diterima'&&<button className="secondary" onClick={()=>handoff(a)}>Handoff</button>}</div>})}</div>)}</div></>}
 {tab==='interviews'&&<><Heading title="Interview & Scorecard" desc="Penjadwalan interview dan penilaian kompetensi terstruktur." action="＋ Jadwalkan Wawancara" onAction={()=>setModal('interview')}/><Table cols={['scheduled_at','interview_type','interviewer_email','status','overall_score']} rows={interviews}/></>}
 {tab==='offers'&&<><Heading title="Manajemen Penawaran" desc="Draft, approval, pengiriman dan keputusan kandidat." action="＋ Buat Offer" onAction={()=>setModal('offer')}/><Table cols={['offer_no','proposed_salary','start_date','status','approved_by']} rows={offers}/><div className="panel table-panel"><div className="table-wrap"><table><tbody>{offers.filter(x=>x.status==='Menunggu Approval').map(o=><tr key={o.id}><td>{o.offer_no}</td><td><Status v={o.status}/></td><td><button className="primary" onClick={()=>decisionOffer(o,true)}>Setujui</button> <button className="secondary" onClick={()=>decisionOffer(o,false)}>Tolak</button></td></tr>)}</tbody></table></div></div></>}
 {tab==='handoff'&&<><Heading title="Serah Terima Onboarding" desc="Kandidat Diterima diserahkan ke proses onboarding tanpa input ulang."/><Table cols={['application_id','target_employee_id','target_start_date','status','created_at']} rows={handoffs}/></>}
 {modal==='req'&&<ReqModal onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{modal==='opening'&&<OpeningModal reqs={reqs.filter(x=>x.status==='Disetujui')} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{modal==='application'&&<ApplicationModal profiles={profiles} openings={openings.filter(x=>x.status==='Open')} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{modal==='candidate'&&<CandidateModal onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{modal==='interview'&&<InterviewModal apps={apps} profiles={profiles} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}{modal==='offer'&&<OfferModal apps={apps} profiles={profiles} onClose={()=>setModal(null)} onSaved={()=>{setModal(null);load()}}/>}</>;
}
function ReqModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({request_no:`REQ-${Date.now().toString().slice(-6)}`,posisi:'',departemen:'',lokasi:'',jumlah_kebutuhan:'1',alasan:'',hiring_manager:'',target_tanggal:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_recruitment_requisitions_v25').insert({...f,jumlah_kebutuhan:Number(f.jumlah_kebutuhan),status:'Menunggu Approval'});if(error)await appAlert(error.message);else onSaved()}return <Modal title="Permintaan Tenaga Kerja" onClose={onClose} onSubmit={save}><label>No. Pengajuan Kebutuhan<input required value={f.request_no} onChange={e=>setF({...f,request_no:e.target.value})}/></label><label>Posisi<input required value={f.posisi} onChange={e=>setF({...f,posisi:e.target.value})}/></label><label>Departemen<input value={f.departemen} onChange={e=>setF({...f,departemen:e.target.value})}/></label><label>Lokasi<input value={f.lokasi} onChange={e=>setF({...f,lokasi:e.target.value})}/></label><label>Jumlah<input type="number" min="1" value={f.jumlah_kebutuhan} onChange={e=>setF({...f,jumlah_kebutuhan:e.target.value})}/></label><label>Hiring Manager<input value={f.hiring_manager} onChange={e=>setF({...f,hiring_manager:e.target.value})}/></label><label>Target Tanggal<input type="date" value={f.target_tanggal} onChange={e=>setF({...f,target_tanggal:e.target.value})}/></label><label>Alasan<textarea value={f.alasan} onChange={e=>setF({...f,alasan:e.target.value})}/></label></Modal>}
function OpeningModal({reqs,onClose,onSaved}:{reqs:Row[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({requisition_id:'',opening_no:`JOB-${Date.now().toString().slice(-6)}`,posisi:'',departemen:'',lokasi:'',employment_type:'Tetap',level_jabatan:'',headcount:'1',salary_min:'0',salary_max:'0',status:'Draft',description:'',requirements:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_recruitment_openings_v25').insert({...f,headcount:Number(f.headcount),salary_min:Number(f.salary_min),salary_max:Number(f.salary_max)});if(error)await appAlert(error.message);else onSaved()}return <Modal title="Pembukaan Lowongan" onClose={onClose} onSubmit={save}><label>Pengajuan Kebutuhan<select required value={f.requisition_id} onChange={e=>{const r=reqs.find(x=>x.id===e.target.value);setF({...f,requisition_id:e.target.value,posisi:r?.posisi||f.posisi,departemen:r?.departemen||f.departemen,lokasi:r?.lokasi||f.lokasi})}}><option value="">Pilih pengajuan kebutuhan</option>{reqs.map(r=><option key={r.id} value={r.id}>{r.request_no} — {r.posisi}</option>)}</select></label><label>No. Job<input required value={f.opening_no} onChange={e=>setF({...f,opening_no:e.target.value})}/></label><label>Posisi<input required value={f.posisi} onChange={e=>setF({...f,posisi:e.target.value})}/></label><label>Departemen<input value={f.departemen} onChange={e=>setF({...f,departemen:e.target.value})}/></label><label>Lokasi<input value={f.lokasi} onChange={e=>setF({...f,lokasi:e.target.value})}/></label><label>Tipe Karyawan<select value={f.employment_type} onChange={e=>setF({...f,employment_type:e.target.value})}><option>Tetap</option><option>Kontrak</option><option>Outsource</option><option>Magang</option></select></label><label>Headcount<input type="number" min="1" value={f.headcount} onChange={e=>setF({...f,headcount:e.target.value})}/></label><label>Gaji Min<input type="number" value={f.salary_min} onChange={e=>setF({...f,salary_min:e.target.value})}/></label><label>Gaji Max<input type="number" value={f.salary_max} onChange={e=>setF({...f,salary_max:e.target.value})}/></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option>Draft</option><option>Open</option><option>Paused</option><option>Closed</option></select></label><label>Deskripsi<textarea value={f.description} onChange={e=>setF({...f,description:e.target.value})}/></label><label>Persyaratan<textarea value={f.requirements} onChange={e=>setF({...f,requirements:e.target.value})}/></label></Modal>}
function CandidateModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({full_name:'',email:'',phone:'',city:'',source:'Job Portal',linkedin_url:'',portfolio_url:'',notes:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_candidate_profiles_v25').insert(f).select('id').single();if(error){await appAlert(error.message);return}onSaved()}return <Modal title="Candidate Profile" onClose={onClose} onSubmit={save}><label>Nama Lengkap<input required value={f.full_name} onChange={e=>setF({...f,full_name:e.target.value})}/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>No. Telepon<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Kota<input value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></label><label>Sumber<select value={f.source} onChange={e=>setF({...f,source:e.target.value})}><option>Job Portal</option><option>Referral</option><option>LinkedIn</option><option>Walk In</option><option>Agency</option></select></label><label>LinkedIn<input value={f.linkedin_url} onChange={e=>setF({...f,linkedin_url:e.target.value})}/></label><label>Portfolio<input value={f.portfolio_url} onChange={e=>setF({...f,portfolio_url:e.target.value})}/></label><label>Catatan<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></Modal>}
function InterviewModal({apps,profiles,onClose,onSaved}:{apps:Row[];profiles:Row[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({application_id:'',interview_type:'Wawancara HR',scheduled_at:`${today()}T09:00`,duration_minutes:'60',location_or_link:'',interviewer_email:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_recruitment_interviews_v25').insert({...f,duration_minutes:Number(f.duration_minutes)});if(error)await appAlert(error.message);else onSaved()}return <Modal title="Jadwalkan Wawancara" onClose={onClose} onSubmit={save}><label>Lamaran<select required value={f.application_id} onChange={e=>setF({...f,application_id:e.target.value})}><option value="">Pilih kandidat</option>{apps.map(a=>{const p=profiles.find(x=>x.id===a.candidate_profile_id);return <option key={a.id} value={a.id}>{p?.full_name||a.id}</option>})}</select></label><label>Jenis Wawancara<input value={f.interview_type} onChange={e=>setF({...f,interview_type:e.target.value})}/></label><label>Waktu<input type="datetime-local" required value={f.scheduled_at} onChange={e=>setF({...f,scheduled_at:e.target.value})}/></label><label>Durasi Menit<input type="number" min="15" value={f.duration_minutes} onChange={e=>setF({...f,duration_minutes:e.target.value})}/></label><label>Lokasi / Link<input value={f.location_or_link} onChange={e=>setF({...f,location_or_link:e.target.value})}/></label><label>Email Pewawancara<input type="email" value={f.interviewer_email} onChange={e=>setF({...f,interviewer_email:e.target.value})}/></label></Modal>}
function OfferModal({apps,profiles,onClose,onSaved}:{apps:Row[];profiles:Row[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({application_id:'',offer_no:`OFF-${Date.now().toString().slice(-6)}`,proposed_salary:'0',start_date:today(),employment_type:'Tetap',status:'Menunggu Approval',notes:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_recruitment_offers_v25').insert({...f,proposed_salary:Number(f.proposed_salary)});if(error)await appAlert(error.message);else onSaved()}return <Modal title="Manajemen Penawaran" onClose={onClose} onSubmit={save}><label>Lamaran<select required value={f.application_id} onChange={e=>setF({...f,application_id:e.target.value})}><option value="">Pilih kandidat</option>{apps.filter(a=>a.stage==='Offering').map(a=>{const p=profiles.find(x=>x.id===a.candidate_profile_id);return <option key={a.id} value={a.id}>{p?.full_name||a.id}</option>})}</select></label><label>No. Offer<input required value={f.offer_no} onChange={e=>setF({...f,offer_no:e.target.value})}/></label><label>Gaji Ditawarkan<input type="number" min="0" value={f.proposed_salary} onChange={e=>setF({...f,proposed_salary:e.target.value})}/></label><label>Tanggal Mulai<input type="date" value={f.start_date} onChange={e=>setF({...f,start_date:e.target.value})}/></label><label>Tipe Karyawan<select value={f.employment_type} onChange={e=>setF({...f,employment_type:e.target.value})}><option>Tetap</option><option>Kontrak</option><option>Outsource</option></select></label><label>Catatan<textarea value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></label></Modal>}

function ApplicationModal({profiles,openings,onClose,onSaved}:{profiles:Row[];openings:Row[];onClose:()=>void;onSaved:()=>void}){const [f,setF]=useState({candidate_profile_id:'',opening_id:'',stage:'Screening',owner_email:''});async function save(e:FormEvent){e.preventDefault();const {error}=await supabase.from('hris_recruitment_applications_v25').insert(f);if(error)await appAlert(error.message);else onSaved()}return <Modal title="Candidate Application" onClose={onClose} onSubmit={save}><label>Candidate<select required value={f.candidate_profile_id} onChange={e=>setF({...f,candidate_profile_id:e.target.value})}><option value="">Pilih kandidat</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.full_name} — {p.email||'—'}</option>)}</select></label><label>Pembukaan Lowongan<select required value={f.opening_id} onChange={e=>setF({...f,opening_id:e.target.value})}><option value="">Pilih job</option>{openings.map(o=><option key={o.id} value={o.id}>{o.opening_no} — {o.posisi}</option>)}</select></label><label>Owner Email<input type="email" value={f.owner_email} onChange={e=>setF({...f,owner_email:e.target.value})}/></label></Modal>}
