import { useEffect, useState, type FormEvent, type ReactNode } from 'react';
import { useTranslation } from '../../../locales/LanguageContext';
import { supabase } from '../../../lib/supabase/client';

type Row=Record<string,any>;
const today=()=>new Date().toISOString().slice(0,10);
function H({title,desc,action,onAction}:{title:string;desc:string;action?:string;onAction?:()=>void}){const {t}=useTranslation();return <div className="page-heading"><div><span className="group-title">{t('group_hr')}</span><h1>{title}</h1><p>{desc}</p></div>{action&&<button className="primary" onClick={onAction}>{action}</button>}</div>}
function St({v}:{v:string}){return <span className={`status ${/reject|tolak|failed|error|expired|closed|inactive/i.test(v)?'red':/draft|pending|queued|warning/i.test(v)?'orange':/active|approved|completed|paid|ready|healthy/i.test(v)?'green':'blue'}`}>{v||'—'}</span>}
function M({title,onClose,onSubmit,children}:{title:string;onClose:()=>void;onSubmit:(e:FormEvent)=>void;children:ReactNode}){const {t}=useTranslation();return <div className="drawer-backdrop"><aside className="edit-drawer"><div className="drawer-head"><div><span>{t('project_by_tirta')}</span><h2>{title}</h2></div><button type="button" className="icon-btn" onClick={onClose}>×</button></div><form className="drawer-body" onSubmit={onSubmit}>{children}<div className="drawer-foot"><button type="button" className="secondary" onClick={onClose}>{t('cancel')}</button><button className="primary">{t('save')}</button></div></form></aside></div>}
const configs:any={
 'v26':{title:'Document & Compliance',desc:'Document lifecycle, expiry monitoring, compliance tasks and secure metadata.',table:'hris_employee_documents_v26',fields:['id_karyawan','document_type','document_no','issue_date','expiry_date','status','storage_path']},
 'v27':{title:'Performance & KPI',desc:'Performance cycles, goals, reviews, calibration and employee scoring.',table:'hris_performance_reviews_v27',fields:['id_karyawan','cycle','goal','weight','score','status']},
 'v28':{title:'HR Analytics & BI',desc:'People metrics, workforce trends and configurable analytics snapshots.',table:'hris_people_analytics_v28',fields:['metric_date','metric_code','dimension','value','target','status']},
 'v29':{title:'Notification & HR Inbox',desc:'Central inbox for approvals, alerts, announcements and action-required events.',table:'hris_hr_inbox_v29',fields:['recipient_email','type','title','message','priority','status']},
 'v30':{title:'ESS Enterprise',desc:'Employee self-service requests, profile actions, documents and manager approvals.',table:'hris_ess_actions_v30',fields:['id_karyawan','action_type','payload','status','requested_at']},
 'v31':{title:'QA & Testing Center',desc:'Application health checks, test runs, defects and release readiness.',table:'hris_qa_test_runs_v31',fields:['run_no','environment','suite','status','passed','failed','duration_ms']},
 'v32':{title:'Production Optimization',desc:'Operational controls for jobs, performance, data quality and release monitoring.',table:'hris_production_jobs_v32',fields:['job_code','schedule','last_run_at','status','duration_ms','message']},
 'v33':{title:'Multi-Company',desc:'Company, branch and tenant-aware organizational foundation.',table:'hris_companies_v33',fields:['code','name','tax_id','timezone','currency','status']},
 'v34':{title:'API & Integrations',desc:'Integration registry, API credentials metadata, webhooks and delivery logs.',table:'hris_integrations_v34',fields:['code','name','provider','type','status','endpoint']},
 'v35':{title:'AI HR & Automation',desc:'Human-supervised HR automation: recommendations, anomaly signals and workflow jobs.',table:'hris_ai_jobs_v35',fields:['job_code','module','input_ref','status','confidence','result_summary']}
};
export default function EnterpriseRoadmapV26V35({version}:{version:keyof typeof configs}){const {t}=useTranslation();const c=configs[version];const [rows,setRows]=useState<Row[]>([]),[modal,setModal]=useState(false),[msg,setMsg]=useState('');const load=async()=>{const {data,error}=await supabase.from(c.table).select('*').order('created_at',{ascending:false}).limit(200);setRows(data||[]);if(error)setMsg(error.message)};useEffect(()=>{load()},[version]);const add=async(e:FormEvent)=>{e.preventDefault();const fd=new FormData(e.currentTarget as HTMLFormElement);const payload:any={};c.fields.forEach((f:string)=>payload[f]=fd.get(f)||null);if(c.table==='hris_employee_documents_v26')payload.id_karyawan=String(payload.id_karyawan||'');if(c.table==='hris_ess_actions_v30')payload.requested_at=new Date().toISOString();const {error}=await supabase.from(c.table).insert(payload);if(error)setMsg(error.message);else{setModal(false);load()}};return <><H title={c.title} desc={c.desc} action={`+ ${t("add")}`} onAction={()=>setModal(true)}/>{msg&&<div className="alert">{msg}</div>}<div className="mini-kpi-row"><div className="stat-card"><span>{t("data")}</span><strong>{rows.length}</strong></div><div className="stat-card"><span>{t("active")}</span><strong>{rows.filter(r=>/active|approved|ready|completed|open/i.test(String(r.status||''))).length}</strong></div><div className="stat-card"><span>{t("pending")}</span><strong>{rows.filter(r=>/pending|draft|queued|warning/i.test(String(r.status||''))).length}</strong></div><div className="stat-card"><span>{t("last_updated")}</span><strong>{rows[0]?.created_at?new Date(rows[0].created_at).toLocaleDateString('id-ID'):'—'}</strong></div></div><div className="panel table-panel"><div className="table-wrap"><table><thead><tr>{c.fields.map((f:string)=><th key={f}>{f.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i}>{c.fields.map((f:string)=><td key={f}>{f==='status'?<St v={String(r[f]??'—')}/>:String(r[f]??'—')}</td>)}</tr>):<tr><td className="empty-cell" colSpan={c.fields.length}>{t("no_data")}</td></tr>}</tbody></table></div></div>{modal&&<M title={`${t("add")} ${c.title}`} onClose={()=>setModal(false)} onSubmit={add}>{c.fields.map((f:string)=><label key={f}>{f.replaceAll('_',' ')}{f==='status'?<select name={f} defaultValue="Draft"><option>Draft</option><option>Aktif</option><option>Menunggu</option><option>Approved</option><option>Completed</option><option>Healthy</option><option>Open</option></select>:<input name={f} type={/date/.test(f)?'date':/weight|score|value|target|passed|failed|duration|confidence/.test(f)?'number':'text'} defaultValue={f==='issue_date'||f==='requested_at'?today():''}/>}</label>)}</M>}</>}
