import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';

import { useTranslation } from '../../../locales/LanguageContext';

type Employee = { id:string; nama:string; jabatan?:string; departemen?:string; status_aktif?:boolean; email?:string };
type Attendance = { id?:string|number; id_karyawan?:string; nama?:string; tanggal?:string; jam_masuk?:string; jam_pulang?:string; status?:string; keterlambatan_menit?:number|string; lembur_menit?:number|string };
type Props = { employees:Employee[]; attendance:Attendance[]; onNavigate:(key:any)=>void };
type Tab = 'executive'|'workforce'|'alerts'|'actions';

const isoToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta'}).format(new Date());
const download=(name:string,content:string,type='text/csv;charset=utf-8')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};

export default function ProfessionalSuite({employees,attendance,onNavigate}:Props){const {t}=useTranslation();
 const [tab,setTab]=useState<Tab>('executive');
 const active=employees.filter(x=>x.status_aktif!==false);
 const today=attendance.filter(x=>x.tanggal===isoToday());
 const late=today.filter(x=>Number(x.keterlambatan_menit||0)>0 || /late|terlambat/i.test(String(x.status||'')));
 const openActions=useMemo(()=>[
   {id:'attendance',title:t('review_attendance_exception'),desc:`${late.length} ${t('attendance_review_needed')}`,tone:late.length?'warning':'good',go:'attendance'},
   {id:'leave',title:t('review_leave_request'),desc:t('open_pending_approval'),tone:'neutral',go:'approvals'},
   {id:'payroll',title:t('payroll_readiness_check'),desc:t('validate_payroll_publish'),tone:'neutral',go:'payroll'},
   {id:'security',title:t('review_security'),desc:t('check_rls_roles_logs'),tone:'neutral',go:'security-v21'},
 ],[late.length]);
 const departments=useMemo(()=>{const m:Record<string,number>={};active.forEach(e=>{const d=e.departemen||t('not_set');m[d]=(m[d]||0)+1});return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,6)},[active]);
 const attendanceRate=active.length?Math.min(100,Math.round(today.length/active.length*100)):0;
 const exportExecutive=()=>{const rows=[[t('metric'),t('value')],[t('active_employees'),String(active.length)],[t('attendance_today'),String(today.length)],[t('attendance_rate'),`${attendanceRate}%`],[t('late_data'),String(late.length)],[t('created_at'),new Date().toISOString()]];download('moonx-executive-report.csv',rows.map(r=>r.join(',')).join('\n'))};
 return <div className="professional-suite">
  <div className="page-heading"><div><span className="eyebrow">{t("professional_operations")}</span><h1>{t("executive_control_center")}</h1><p>{t("executive_control_desc")}</p></div><div className="heading-actions"><button className="secondary" onClick={exportExecutive}>{t("export_executive_report")}</button><button className="primary" onClick={()=>onNavigate('reports')}>{t("open_reporting")}</button></div></div>
  <div className="branch-tabs">{([['executive',t('executive')],['workforce',t('employee')],['alerts',t('risk_alerts')],['actions',t('action_center')]] as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
  {tab==='executive'&&<>
   <div className="stat-grid executive-stats"><div className="stat-card"><span>{t("active_employees")}</span><strong>{active.length}</strong><small>{employees.length-active.length} {t("inactive")}</small></div><div className="stat-card"><span>{t("attendance_today")}</span><strong>{attendanceRate}%</strong><small>{today.length} {t("recorded_data")}</small></div><div className="stat-card"><span>{t("needs_attention")}</span><strong>{late.length}</strong><small>{t("needs_review")}</small></div><div className="stat-card"><span>{t("attendance_per_employee")}</span><strong>{employees.length?Math.round(attendance.length/Math.max(1,employees.length)):'0'}</strong><small>{t("data_per_employee")}</small></div></div>
   <div className="dashboard-grid-top"><div className="panel"><div className="panel-head"><div><span className="eyebrow">{t("employee_composition")}</span><h2>{t("organization")}</h2><p>{t("employee_distribution")}</p></div></div><div className="department-bars">{departments.length?departments.map(([d,n])=><div className="dept-row" key={d}><div className="dept-label"><span>{d}</span><b>{n}</b></div><div className="progress"><span style={{width:`${Math.round(n/Math.max(...departments.map(x=>x[1]))*100)}%`}}/></div></div>):<div className="empty-module"><h3>{t("no_data")}</h3><p>{t("department_after_workforce")}</p></div>}</div></div><div className="panel attendance-health"><div className="panel-head"><div><span className="eyebrow">{t("operational_readiness")}</span><h2>{t("operational_readiness")}</h2><p>{t("readiness_desc")}</p></div></div><div className="health-ring" style={{'--rate':`${attendanceRate*3.6}deg`} as CSSProperties}><div><strong>{attendanceRate}%</strong><small>{t("coverage")}</small></div></div><div className="health-legend"><div><i className="dot present"/><span>{t("attendance_recorded")}</span><b>{today.length}</b></div><div><i className="dot late"/><span>{t("needs_attention")}</span><b>{late.length}</b></div><div><i className="dot absent"/><span>{t("active_employees")}</span><b>{active.length}</b></div></div></div></div>
   <div className="dashboard-grid-bottom"><div className="panel"><div className="panel-head"><div><span className="eyebrow">{t("recent_activity")}</span><h2>{t("attendance_activity")}</h2></div><button className="link-btn" onClick={()=>onNavigate('attendance')}>{t("view_all")}</button></div><div className="table-wrap"><table><thead><tr><th>{t("employee")}</th><th>{t('date')}</th><th>{t("check_in")}</th><th>{t("status")}</th></tr></thead><tbody>{attendance.slice(0,8).map((a,i)=><tr key={a.id||i}><td><b>{a.nama||a.id_karyawan||'—'}</b></td><td>{a.tanggal||'—'}</td><td>{a.jam_masuk||'—'}</td><td><span className="status">{a.status||t("recorded")}</span></td></tr>)}{!attendance.length&&<tr><td colSpan={4}>{t("no_activity")}</td></tr>}</tbody></table></div></div><div className="panel quick executive-quick"><div className="panel-head"><div><span className="eyebrow">{t("quick_workflow")}</span><h2>{t("main_process")}</h2></div></div><button className="quick-action" onClick={()=>onNavigate('employee-add')}>{t("add_employee")} <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('approvals')}>{t("approval_center")} <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('audit')}>{t("audit_activity")} <span>›</span></button><button className="quick-action" onClick={()=>onNavigate('system-health')}>{t("system_health")} <span>›</span></button></div></div>
  </>}
  {tab==='workforce'&&<div className="panel table-panel"><div className="panel-head"><div><span className="eyebrow">{t("employee_roster_data")}</span><h2>{t("employee_data_quality")}</h2><p>{t("data_quality_check_desc")}</p></div></div><div className="table-wrap"><table><thead><tr><th>{t("name")}</th><th>{t("department")}</th><th>{t("email")}</th><th>{t("status")}</th><th>{t("quality")}</th></tr></thead><tbody>{employees.map(e=>{const issues=[!e.email?t('email_empty'):'',!e.departemen?t('department_empty'):'',!e.jabatan?t('position_empty'):''].filter(Boolean);return <tr key={e.id}><td><b>{e.nama}</b></td><td>{e.departemen||'—'}</td><td>{e.email||'—'}</td><td>{e.status_aktif===false?t("inactive"):t("active")}</td><td><span className={`status ${issues.length?'orange':'green'}`}>{issues.length?`${issues.length} ${t("issues")}`:t("ready")}</span></td></tr>})}</tbody></table></div></div>}
  {tab==='alerts'&&<div className="content-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">{t("risk_monitor")}</span><h2>{t("attention")}</h2><p>{t("data_signals_desc")}</p></div></div>{late.length?<div className="alert-list">{late.slice(0,20).map((a,i)=><div className="alert-row" key={a.id||i}><span className="status orange">{t("review")}</span><div><b>{a.nama||a.id_karyawan||t('employee')}</b><small>{a.tanggal||t('today')} · {t('late')} {Number(a.keterlambatan_menit||0)} {t('minutes')}</small></div><button className="link-btn" onClick={()=>onNavigate('late')}>{t("open")}</button></div>)}</div>:<div className="empty-module"><h3>{t("no_exceptions_today")}</h3><p>{t("no_late_attendance")}</p></div>}</div><div className="panel"><div className="panel-head"><div><span className="eyebrow">{t("data_quality")}</span><h2>{t("checklist")}</h2></div></div><div className="check-list"><div><b>{t("employee_data_available")}</b><span className="status green">{t("ok")}</span></div><div><b>{t("attendance_data")}</b><span className={`status ${today.length?'green':'orange'}`}>{today.length?t('ok'):t('review')}</span></div><div><b>{t("contact_completeness")}</b><span className={`status ${employees.filter(e=>e.email).length===employees.length?'green':'orange'}`}>{employees.filter(e=>e.email).length}/{employees.length}</span></div></div></div></div>}
  {tab==='actions'&&<div className="content-grid"><section className="web-card-group"><div className="panel-head"><div><span className="eyebrow">{t("action_center_upper")}</span><h2>{t("today_work_queue")}</h2><p>{t("hr_shortcuts_desc")}</p></div></div><div className="action-card-grid">{openActions.map(a=><button className="action-card" key={a.id} onClick={()=>onNavigate(a.go)}><span className={`status ${a.tone==='warning'?'orange':a.tone==='good'?'green':'blue'}`}>{a.tone==='warning'?t('needs_attention'):t('ready')}</span><b>{a.title}</b><small>{a.desc}</small><em>{t("open_workflow")}</em></button>)}</div></section><div className="panel"><div className="panel-head"><div><span className="eyebrow">{t("next_phase")}</span><h2>{t("database_automation")}</h2><p>{t("database_automation_desc")}</p></div></div><ul className="roadmap-list"><li>{t("approval_queue_storage")}</li><li>{t("notification_preferences")}</li><li>{t("audit_event_storage")}</li><li>{t("scheduled_hr_work")}</li><li>{t("ai_anomaly_detection")}</li></ul></div></div>}
 </div>;
}
